<a href="https://colab.research.google.com/github/kabirulislam95/AI/blob/main/Assainment04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://github.com/kabirulislam95/AI/blob/main/Assainment04.ipynb)

In [ ]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import load_iris
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [42]:
# Importing the dataset
data = sns.load_dataset("iris")
data.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [43]:
# Splitting the dataset into the Training set and Test set
# X = feature values, all the columns except the last column
X = data.iloc[:, :-1]

# y = target values, last column of the data frame
y = data.iloc[:, -1]

In [44]:
X

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [45]:
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [46]:
#Split the data into 80% training and 20% testing
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [47]:
#Train the model
model = LogisticRegression(solver='lbfgs', max_iter=1000)
model.fit(x_train, y_train) #Training the model

LogisticRegression(max_iter=1000)

In [48]:
predictions = model.predict(x_test)
predictions

array(['versicolor', 'setosa', 'virginica', 'versicolor', 'versicolor',
       'setosa', 'versicolor', 'virginica', 'versicolor', 'versicolor',
       'virginica', 'setosa', 'setosa', 'setosa', 'setosa', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa',
       'virginica', 'setosa', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'setosa', 'setosa'], dtype=object)

In [49]:
accuracy_score(y_test, predictions)

1.0

**SUPPORT VECTOR** **MACHIME** **bold text**

In [57]:
from sklearn import svm
model=svm.SVC(kernel = 'linear', C=1)

In [58]:
model.fit(x_train, y_train)

SVC(C=1, kernel='linear')

In [59]:
pred=model.predict(x_test)

In [60]:
accuracy_score(y_test, pred)

1.0

knn ** **bold text****

In [63]:
from sklearn.neighbors import KNeighborsClassifier

In [68]:
knnmodel = KNeighborsClassifier(n_neighbors = 3)
knnmodel.fit(x_train, y_train)
y_predict1 = knnmodel.predict(x_test)

In [69]:
accuracy_score(y_test, y_predict1)

1.0

**Neuro Network**

In [108]:
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense
from tensorflow.keras.optimizers import Adam

In [109]:
nmodel = Sequential()
nmodel.add(Dense(3, input_dim=4, activation='relu'))
nmodel.add(Dense(5, activation='relu'))
nmodel.add(Dense(3, activation='softmax'))

In [110]:
nmodel.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acuracy'])

In [111]:
nmodel.summary

<bound method Model.summary of <keras.engine.sequential.Sequential object at 0x7ff1c9827610>>

In [112]:
nmodel.get_weights()

[array([[ 0.15339375, -0.7002715 ,  0.24321616],
        [-0.6033621 ,  0.448681  ,  0.0364604 ],
        [-0.25716132,  0.20640469, -0.41378665],
        [ 0.47337747, -0.28764808,  0.1902535 ]], dtype=float32),
 array([0., 0., 0.], dtype=float32),
 array([[-0.512246  ,  0.15481657, -0.06092155,  0.09478801,  0.05266058],
        [ 0.75678605,  0.40727824,  0.1321904 ,  0.28020352,  0.17466718],
        [ 0.36149484, -0.18925059,  0.23524553, -0.21457827, -0.28465867]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32),
 array([[ 0.03819525, -0.40502706, -0.82395846],
        [-0.44224778, -0.6894033 , -0.7427137 ],
        [-0.04630548,  0.55920535,  0.7537331 ],
        [ 0.20301026, -0.46543983,  0.43282026],
        [-0.50078344, -0.3848694 , -0.17951089]], dtype=float32),
 array([0., 0., 0.], dtype=float32)]

In [102]:
from tensorflow import keras


In [113]:
from keras.layers.core.lambda_layer import Lambda
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y1 = encoder.fit_transform(y)
Y = pd.get_dummies(y1).values

In [114]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [115]:
nmodel.fit(x_train, y_train, epochs=300)

Epoch 1/300


ValueError: ignored