<a href="https://colab.research.google.com/github/kabirulislam95/AI/blob/main/Assainment04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://github.com/kabirulislam95/AI/blob/main/Assainment04.ipynb\)

In [77]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import load_iris
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.svm import SVC
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split


### **Part1: Load the dataset**

In [36]:
# Importing the dataset
data = sns.load_dataset("iris")
#print top 15 of the dataset
data.head(15)

sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa

In [20]:
#print the summary of the dataset
data.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

### **About the dataset**
for each data it has four different variables, sepal_length, sepal_width, petal_length and petal_width. Based of these four variables, each flower belongs to a particular species. In our dataset, it has three dirrent types of species, setosa, versicolor and virginica.

The four variables are the features and 'species' is the labels. Based on the four features, each new data would be label as setaso or versicolor or virginica.

### **Part2: Split the dataset**

In [38]:
# Splitting the dataset into the Training set and Test set
# X = feature values, all the columns except the last column
X = data.iloc[:, :-1]

# y = target/label values, last column of the dataset
y = data.iloc[:, -1]

In [39]:
#print first 5 features value
X.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [40]:
#print first 5 label values
y.head()

0    setosa
1    setosa
2    setosa
3    setosa
4    setosa
Name: species, dtype: object

In [45]:
#Split the data into 90% training and 10% testing
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=0)

### **Part3: Logistic Regression**

In [53]:
#take logostic regression model object
model_lregression = LogisticRegression(max_iter=1000)
#Training the model
model_lregression.fit(x_train.values, y_train.values) 

LogisticRegression(max_iter=1000)

In [65]:
#probability of each species
pd.DataFrame(model_lregression.predict_proba([[1, 2, 3, 4]]), columns = ["Setosa", "Versicolor", "Virginica"])

Setosa  Versicolor  Virginica
0  0.052595    0.017443   0.929961

In [58]:
#Creating samples
sample1 = np.array([[4.9, 3.0, 1.5, 0.2]])
sample2 = np.array([[4.9, 2.5, 3.2, 1.1]])
sample3 = np.array([[4.9, 2.9, 4.5, 1.9]])

In [59]:
#predict sample1
model_lregression.predict(sample1)

array(['setosa'], dtype=object)

In [61]:
#predict sample2
model_lregression.predict(sample2)

array(['versicolor'], dtype=object)

In [68]:
#predict sample3
model_lregression.predict(sample3)

array(['virginica'], dtype=object)

In [72]:
#ficd accuracy score
model_lregression.score(x_test.values, y_test)

1.0

In [73]:
#coefficient
model_lregression.coef_

array([[-0.41087786,  0.92630746, -2.43464502, -1.04770092],
       [ 0.40315462, -0.32623036, -0.11363406, -0.88710526],
       [ 0.00772324, -0.6000771 ,  2.54827907,  1.93480618]])

In [74]:
#intercept
model_lregression.intercept_

array([  9.46338452,   2.44534908, -11.9087336 ])

### **Part4: Support Vector Machine**

In [79]:
#create SVM model object
model_svm=svm.SVC(kernel = 'linear', C=1)

In [80]:
#train the model
model_svm.fit(x_train, y_train)

SVC(C=1, kernel='linear')

In [59]:
pred=model.predict(x_test)

In [60]:
accuracy_score(y_test, pred)

1.0

knn ** **bold text****

In [63]:
from sklearn.neighbors import KNeighborsClassifier

In [68]:
knnmodel = KNeighborsClassifier(n_neighbors = 3)
knnmodel.fit(x_train, y_train)
y_predict1 = knnmodel.predict(x_test)

In [69]:
accuracy_score(y_test, y_predict1)

1.0

**Neuro Network**

In [108]:
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense
from tensorflow.keras.optimizers import Adam

In [109]:
nmodel = Sequential()
nmodel.add(Dense(3, input_dim=4, activation='relu'))
nmodel.add(Dense(5, activation='relu'))
nmodel.add(Dense(3, activation='softmax'))

In [110]:
nmodel.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acuracy'])

In [111]:
nmodel.summary

<bound method Model.summary of <keras.engine.sequential.Sequential object at 0x7ff1c9827610>>

In [112]:
nmodel.get_weights()

[array([[ 0.15339375, -0.7002715 ,  0.24321616],
        [-0.6033621 ,  0.448681  ,  0.0364604 ],
        [-0.25716132,  0.20640469, -0.41378665],
        [ 0.47337747, -0.28764808,  0.1902535 ]], dtype=float32),
 array([0., 0., 0.], dtype=float32),
 array([[-0.512246  ,  0.15481657, -0.06092155,  0.09478801,  0.05266058],
        [ 0.75678605,  0.40727824,  0.1321904 ,  0.28020352,  0.17466718],
        [ 0.36149484, -0.18925059,  0.23524553, -0.21457827, -0.28465867]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32),
 array([[ 0.03819525, -0.40502706, -0.82395846],
        [-0.44224778, -0.6894033 , -0.7427137 ],
        [-0.04630548,  0.55920535,  0.7537331 ],
        [ 0.20301026, -0.46543983,  0.43282026],
        [-0.50078344, -0.3848694 , -0.17951089]], dtype=float32),
 array([0., 0., 0.], dtype=float32)]

In [102]:
from tensorflow import keras


In [113]:
from keras.layers.core.lambda_layer import Lambda
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y1 = encoder.fit_transform(y)
Y = pd.get_dummies(y1).values

In [114]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [115]:
nmodel.fit(x_train, y_train, epochs=300)

Epoch 1/300


ValueError: ignored